alias docker="sudo docker"
alias cmd-node1="docker exec -it node1"
alias cmd-node2="docker exec -it node2"
alias cmd-node1-query="cmd-node1 guldenserver/Gulden-cli -rpcuser=santa -rpcpassword=secret -rpcconnect=127.0.0.1 -rpcport=9231"
alias cmd-node2-query="cmd-node2 guldenserver/Gulden-cli -rpcuser=santa -rpcpassword=secret -rpcconnect=127.0.0.1 -rpcport=9231"
alias watch-wallet-node1="sudo watch -n1 docker exec -it node1 guldenserver/Gulden-cli -rpcuser=santa -rpcpassword=secret -rpcconnect=127.0.0.1 -rpcport=9231 getwalletinfo"
alias watch-wallet-node2="sudo watch -n1 docker exec -it node2 guldenserver/Gulden-cli -rpcuser=santa -rpcpassword=secret -rpcconnect=127.0.0.1 -rpcport=9231 getwalletinfo"
alias trx-all-funds="sudo bash /home/vagrant/transferall.sh"
alias watch-trx-node-1="sudo watch -n1 docker exec -it node1 guldenserver/Gulden-cli -rpcuser=santa -rpcpassword=secret -rpcconnect=127.0.0.1 -rpcport=9231 listtransactions"
alias watch-trx-node-2="sudo watch -n1 docker exec -it node2 guldenserver/Gulden-cli -rpcuser=santa -rpcpassword=secret -rpcconnect=127.0.0.1 -rpcport=9231 listtransactions"